apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: greenturtle-dotnet60-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: greenturtle-dotnet60-sample
    app.kubernetes.io/part-of: greenturtle
  name: greenturtle-dotnet60-sample
  namespace: pdave
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: greenturtle-dotnet60-sample
    weight: 100
status: {}
