apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    build.appstudio.openshift.io/application: greenturtle
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: greenturtle-dotnet60-sample
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: greenturtle-dotnet60-sample
  namespace: pdave
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: greenturtle-dotnet60-sample
status:
  configuration:
    generatedName: ""
